version: 2
updates:
  - package-ecosystem: 'pip'
    directory: '/pulumi'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'Kravalg'
    groups:
      all-deps:
        patterns:
          - '*'
    commit-message:
      prefix: 'feat'
      prefix-development: 'chore'
      include: 'scope'
