version: '3.8'

services:
  terraform:
    image: hashicorp/terraform:1.3.6
    volumes:
      - ../terraform:/infra
    working_dir: /infra
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}

  terraspace:
#    user: "${UID}:${GID}"
    image: boltops/terraspace:2.2.2-ubuntu
    volumes:
      - ../terraform:/infra
    working_dir: /infra

  terraform-compliance:
    image: eerkunt/terraform-compliance:1.3.34