version = "0.1.0"

[build-system]
requires = [ "poetry-core" ]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false

  [tool.poetry.dependencies]
  pulumi = "^3.181"
  pulumi-aws = "^6.83"
  python = "^3.9"
  black = "^25.1.0"
  flake8 = "^7.3.0"
  pre-commit = "^4.2.0"
